/**
 * FileMonitoring.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArquivoDto { 
    id?: number;
    nomeArquivo?: string | null;
    dataRecebimento?: string;
    dataExpiracao?: string | null;
    status?: string | null;
    tipoAdquirente?: string | null;
    tamanhoBytes?: number;
    mensagemErro?: string | null;
    quantidadeTransacoes?: number;
}

