/**
 * FileMonitoring.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EstatisticasDto { 
    totalArquivos?: number;
    arquivosRecepcionados?: number;
    arquivosNaoRecepcionados?: number;
    percentualSucesso?: number;
    porAdquirente?: { [key: string]: number; } | null;
}

