/**
 * FileMonitoring.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransacaoArquivoDto { 
    id?: number;
    tipoRegistro?: string | null;
    estabelecimento?: string | null;
    dataProcessamento?: string;
    periodoInicial?: string;
    periodoFinal?: string;
    sequencia?: string | null;
    empresa?: string | null;
}

