/**
 * FileMonitoring.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArquivoDto } from './arquivoDto';


export interface UploadResultDto { 
    sucesso?: boolean;
    mensagem?: string | null;
    arquivo?: ArquivoDto;
}

